spring:
  datasource:
    url: jdbc:mysql://localhost:3306/rhymni
    username: root
    password:
    driver-class-name: com.mysql.jdbc.Driver
  jpa:
    database-platform: org.hibernate.dialect.MySQL5InnoDBDialect
    hibernate:
      ddl-auto: update
  security:
    basic:
      enabled: false
