name: Frontend CI

on:
  push:
    branches: [main]
    paths:
      - "rhymni-front/**"
  pull_request:
    branches: [main]
    paths:
      - "rhymni-front/**"

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v2
      - name: Setup Node.js environment
        uses: actions/setup-node@v2
        with:
          node-version: "14"
      - name: Install dependencies
        run: cd rhymni-front && npm install
      - name: Build project
        run: cd rhymni-front && npm run build
